apiVersion: v1
kind: ConfigMap
metadata:
  name: trading-strategy
  namespace: default
data:
  strategy.type: HFT
  strategy.maxVolume: "5000"
  strategy.risk: high
  instructor-1: Muhammad Ali Kahoot
  instructor-2: Usama Ahmed
